config/routes.rb
Rails.application.routes.draw do
	
  get 'activities/index'

  devise_for :users

  resources :clearance_batches do #, only: [:index, :create, :destroy]
  	resources :items          
  end
  
  resources :activities

  root "clearance_batches#index" 

  match '/mybatches', to: 'clearance_batches#mybatches', via: :get  
  match '/buy/:id', to: 'clearance_batches#buybatch', via: :get  
  match '/undobatch/:id', to: 'clearance_batches#undobatch', via: :get  

  match '/staffperformance', to: 'pages#staffperformance', via: :get  

  #match '/usecsv', to: 'pages#usecsv', via: :get

  resources :pages, only: [:index, :create, :staffperformance]
  
  

end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

	include PublicActivity::Model
	tracked owner: ->(controller, model){controller && controller.current_user}
	
	has_many :items, dependent: :destroy
	belongs_to :user



  def buy!
    update_attributes!(status: true)

  end

  def undo!
  	update_attributes!(status: false)
  end

  def self.search(params)
    if params 
      self.where("id like ?", "%#{params}%")
    else
      self.all
    end
  end
 

end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create,:buybatch, :destroy ]
  

  def index
    @clearance_batches  = ClearanceBatch.all    
    @clearance_batches = @clearance_batches.search(params[:search]) if params[:search].present?
    
    @itemssearch = Item.search(params[:searchitem]) if params[:searchitem].present?
  end

  def new    
      @clearance = ClearanceBatch.new    
  end

  def create
    if user_signed_in?
      if current_user.role != "vendor" 
        @clearance_batch = ClearanceBatch.new    
        @clearance_batch.save
        redirect_to action: :index
        flash[:alert] = "New Batch Created"
      else      
        redirect_to action: :index
        flash[:alert] = "Sorry, You Are Not Allowed To Create A Batch"
      end          
    else      
      redirect_to action: :index
      flash[:alert] = "Sorry, You Are Not Allowed To Create A Batch"
    end      
  end


  def destroy    
      if current_user.role != "vendor"         
        @clearance_des = ClearanceBatch.find(params[:id])

        if @clearance_des.status == false
          @clearance_des.destroy
          redirect_to action: :index
          flash[:alert] = "Batch Deleted"
        else
          redirect_to action: :index
        end
      else      
        redirect_to action: :index
        flash[:alert] = "Sorry, You Are Not Allowed To Create A Batch"
      end    
  end

  def buybatch    
      if current_user.role == "vendor" 
        @mybatch = ClearanceBatch.find(params[:id])
        @mybatch.user = current_user
        @mybatch.buy!
        @mybatch.save
        
        redirect_to action: :index
        flash[:alert] = "You Bought Batch Number #{params[:id]}"
      else
        redirect_to action: :index
        flash[:alert] = "You Cant buy an item"
      end
  end

  def undobatch
      if current_user.role == "vendor" 
        @mybatch = ClearanceBatch.find(params[:id])
        @mybatch.user = nil
        @mybatch.undo!
        @mybatch.save
        
        redirect_to action: :index
        flash[:alert] = "Okay! We Understand, You dont need Batch #{params[:id]}, We Will Refund the Money Soon"
      else
        redirect_to action: :index
        flash[:alert] = "You Cant buy an item"
      end
  end



  def show
    @clearance_in = ClearanceBatch.find(params[:id])
    @items =  Item.where(clearance_batch_id: params[:id])
    @items = @items.search(params[:search]) if params[:search].present?
    @items =  @items.order(created_at: :desc)    

  end

  def mybatches
    @mybatches = ClearanceBatch.where(user: current_user)        
  end

end

app/views/clearance_batches/_createbatch.html.erb
<% if user_signed_in? %> 
	<% unless current_user.role == "vendor" %>
		<table class="table table-striped clearance_batches">
		<div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black">
		  <div class="card-block">
		  
		    <%= link_to 'CREATE A BATCH', new_clearance_batch_path %>
		  
		  </div>
		</div>
		</table>
	<% end %>
<% end %>

app/views/clearance_batches/_createitem.html.erb
<% if user_signed_in? %> 
	<% unless current_user.role == "vendor" %>
		<%= link_to 'CREATE A NEW ITEM', new_clearance_batch_item_path(@clearance_in.id) %>
	<% end %>
<% end %>

app/views/clearance_batches/_optionusertype.html.erb
<% if user_signed_in? %> 
  <% if current_user.role != "vendor"  %>
      <% if clearance_batch.status == true %>
        <p class = "btn btn-primary">BATCH SOLD</p>            
      <% else %>
        <%= link_to 'Delete Batch',  "/clearance_batches/#{clearance_batch.id}", data: {confirm: "Wait! Are you sure ?"}, method: :delete, class: "btn btn-primary"  %>
            <p class = "btn btn-primary">TO BE SOLD</p>
      <% end %>

  <% else %>

    <% if clearance_batch.status == false %>
        <a href="/buy/<%= clearance_batch.id %>" class="btn btn-primary">BUY BATCH</a>
    <% else %>
        <p class = "btn btn-primary">ITEM SOLD</p>              
    <% end %>
  <% end %>        
<% end %>
      

app/views/clearance_batches/index.html.erb
<div class = "container">
<% if @itemssearch != nil %>
<h2>ITEM SEARCH RESULTS </h2>
  <% @itemssearch.each do |item| %>

    <div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
      <div class="card-block">

        <h3 class="card-title">barcode ID: <%= item.id %></h3>          
        <p class="card-text">Size: <%= item.size %></p>
         <div class="card text-center" style="width: 2rem; height: 2rem; border: 1px solid black; background-color: <%= item.color if item.color %>; "></div> 
        
        <p class="card-text">Color: <%= item.color %></p>            
        
        <%= render 'items/status', :item => item %>

        <p class="card-text">Clearance Batch id: <%= item.clearance_batch_id.to_i if item.clearance_batch_id.to_i %></p>
        <p class="card-text">Created At: <%= l(item.created_at, format: :short) %></p>      
        <p class="card-text">Updated At: <%= l(item.updated_at, format: :short) %></p>

        <%= render 'items/shared', :batchid => item.clearance_batch_id.to_i, :itemid => item.id %>  

        <%= link_to 'Show', clearance_batch_item_path(item.clearance_batch_id.to_i,item.id) if item.clearance_batch_id.to_i > 0 %>
         
      </div>
    </div>

  <% end %>
<% end %>

<hr>

</div>

<div class = "container">

<h2>CLEARANCE BATCHES</h2>

<%= render 'clearance_batches/createbatch' %>

<%- @clearance_batches.each do |clearance_batch| -%>

  <div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
    <div class="card-block">

      <h3 class="card-title">Clearance Batch <%= clearance_batch.id %></h3>  
      <p class="card-text">Created at: <%= l(clearance_batch.created_at, format: :short) %></p>
      <p class="card-text">Item Count: <%= clearance_batch.items.count %></p>     
            
      <a href="/clearance_batches/<%= clearance_batch.id %>" class="btn btn-primary">Add/View Items</a>

      <hr>    
      <%= render 'clearance_batches/optionusertype', :clearance_batch => clearance_batch %>

    </div>
  </div>

  <%- end -%>

</div>

app/views/clearance_batches/mybatches.html.erb
<h2>MY BATCHES</h2>

<%- @mybatches.each do |clearance_batch| -%>

  <div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
    <div class="card-block">

      <h3 class="card-title">Clearance Batch <%= clearance_batch.id %></h3>  
      <p class="card-text">Created at: <%= l(clearance_batch.created_at, format: :short) %></p>
      <p class="card-text">Item Count: <%= clearance_batch.items.count %></p>             
      
      <hr>

      <a href="/clearance_batches/<%= clearance_batch.id %>" class="btn btn-primary">VIEW ALL ITEMS</a>
      <hr>
      <a href="/undobatch/<%= clearance_batch.id %>" class="btn btn-primary">UNDO BUY</a>
            
    </div>
  </div>

  <%- end -%>






app/views/clearance_batches/new.html.erb

<%= form_for @clearance, :html => {:multipart => true}, class: 'form-inline' do |f| %>  
  <%= button_tag 'Create new batch', class: 'btn btn-primary' %>
<% end %>

app/views/clearance_batches/show.html.erb
<%= render 'clearance_batches/createitem' %>


<h2 >CLEARANCE BATCH NUMBER <%= @clearance_in.id %> </h2>
<% if @items.present? %>
	<% @items.each do |item| %>

		<div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
	    <div class="card-block">

	      <h3 class="card-title">barcode ID: <%= item.id %></h3> 	      	
	      <p class="card-text">Size: <%= item.size %></p>
	       <div class="card text-center" style="width: 2rem; height: 2rem; border: 1px solid black; background-color: <%= item.color if item.color %>; "></div>	
	      
	      <p class="card-text">Color: <%= item.color %></p>	     
	      
	      
	      	<%= render 'items/status', :item => item %>

		<p class="card-text">Clearance Batch id: <%= item.clearance_batch_id.to_i if item.clearance_batch_id.to_i %></p>	 
		<p class="card-text">Created At: <%= l(item.created_at, format: :short) %></p>      
	      <p class="card-text">Updated At: <%= l(item.updated_at, format: :short) %></p>

	      	<%= render 'items/shared', :batchid => @clearance_in.id, :itemid => item.id %>	      	

	      <%= link_to 'Show', clearance_batch_item_path(@clearance_in.id,item.id) %>
	    </div>
	  </div>

	<% end %>
<% end %>

