config/routes.rb
Rails.application.routes.draw do
	
  get 'activities/index'

  devise_for :users

  resources :clearance_batches do #, only: [:index, :create, :destroy]
  	resources :items          
  end
  
  resources :activities

  root "clearance_batches#index" 

  match '/mybatches', to: 'clearance_batches#mybatches', via: :get  
  match '/buy/:id', to: 'clearance_batches#buybatch', via: :get  
  match '/undobatch/:id', to: 'clearance_batches#undobatch', via: :get  

  match '/staffperformance', to: 'pages#staffperformance', via: :get  

  #match '/usecsv', to: 'pages#usecsv', via: :get

  resources :pages, only: [:index, :create, :staffperformance]
  
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  

  include PublicActivity::Model
  tracked owner: ->(controller, model){controller && controller.current_user}

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :user
  belongs_to :clearance_batch
  validates :id, :uniqueness => true



  


  scope :sellable, -> { where(status: 'sellable') }

  def clearance!
    update_attributes!(status: 'clearanced', 
                       price_sold: style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE)
  end

  def setestimatedprice!
  	update_attributes!(status: 'sellable', price_sold: style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE)
  end
  
  def self.search(params)
    if params 
      self.where("id like ?", "%#{params}%")
    else
      self.all
    end
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all    
  end

  # GET /items/1
  def show
    @batch = ClearanceBatch.find(params[:clearance_batch_id])
    @item = @batch.items.find(params[:id])
    @style = Style.find_by_id(@item.style_id)
    
  end

  # GET /items/new
  def new
  	@batch = ClearanceBatch.find(params[:clearance_batch_id])
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @batch = ClearanceBatch.find(params[:clearance_batch_id])
    @item = @batch.items.find(params[:id])
  end

  # POST /items
  def create    
      if current_user.role != "vendor" 

        @batch = ClearanceBatch.find(params[:clearance_batch_id])
        @item = @batch.items.new(item_params)
        @item.user = current_user
        

        if @item.save
          if @item.status.eql? "clearanced"
              @item.clearance!
          end

          if @item.status.eql? "sellable"
                @item.setestimatedprice!
          end

          redirect_to @batch, notice: 'Item was successfully created.'
        else      
          render :new
        end
      else
        redirect_to action: :index
        flash[:alert] = "Sorry, You Are Not Allowed To Create An Item"
      end    
  end

  # PATCH/PUT /items/1
  def update    
      if current_user.role != "vendor" 
        @batch = ClearanceBatch.find(params[:clearance_batch_id])
        @item = @batch.items.find(params[:id])
        @item.user = current_user

        if @item.update_attributes(item_params)
          if @item.status.eql? "clearanced"
            @item.clearance!
          elsif @item.status.eql? "sellable"
            @item.setestimatedprice!
          end

          redirect_to @batch, notice: 'Item was successfully updated.'
          
        else
          render :edit
        end
      else
        redirect_to action: :index
        flash[:alert] = "Sorry, You Are Not Allowed To Update An Item"
      end   
  end

  # DELETE /items/1
  def destroy    
      if current_user.role != "vendor"
        @batch = ClearanceBatch.find(params[:clearance_batch_id])
        @item = @batch.items.find(item_params)

        @item.destroy
        redirect_to @batch, notice: 'Item was successfully destroyed.'
      else
        redirect_to action: :index
        flash[:alert] = "Sorry, You Are Not Allowed To Delete An Item"
      end    
  end

  def search    
    @items = Item.search(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:id, :size, :price_sold, :sold_at, :color, :status, :style_id)
    end

    
end

app/helpers/items_helper.rb
module ItemsHelper
	def properlinks
		
	end
end

app/views/items/_form.html.erb
<%= form_for [@batch, @item]  do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>    
  <% end %>


<div class="container">
<div class="form-group row">  
  <div class="col-10">
    <%= f.label :id, 'Barcode Id', class: 'col-2 col-form-label' %>
    <%= f.text_field :id %>

  </div>
</div>


<div class="form-group row">  
  <div class="col-10">

    <%= f.label :size, class: 'col-2 col-form-label' %> 
    <%= f.select :size, ["S","M", "L", "XL", "XXL"]%>

  </div>
</div>

  
<div class="form-group row">  
  <div class="col-10">

    <%= f.label :color, class: 'col-2 col-form-label' %>
    <%= f.text_field :color%>

  </div>
</div>

<div class="form-group row">  
  <div class="col-10">

    <%= f.label :price_sold, 'Price Sold (Fill Only When Items Bought By Clients)', class: 'col-2 col-form-label' %>

    <%= f.text_field :price_sold%>

  </div>
</div>


  
<div class="form-group row">  
  <div class="col-10">
    <%= f.label :status, class: 'col-2 col-form-label' %>    
    <%= f.select :status, ["sellable","clearanced","not sellable", "sold", ]%>
  </div>
</div>



<div class="form-group row">  
  <div class="col-10">

    <%= f.label :style_id, class: 'col-2 col-form-label' %>
    <%= f.select :style_id, Style.all.map{ |f| [f.name, f.id]}%>
  </div>
</div>





  
<div class="form-group row">  
  <div class="col-10">
    <%= f.submit 'Submit', class: 'btn btn-primary'%>
  </div>
</div>


</div>
<% end %>

app/views/items/_shared.html.erb
<% if user_signed_in? %> 
	<% unless current_user.role == "vendor" %>
		<%= link_to 'Edit', edit_clearance_batch_item_path(batchid,itemid) if batchid.to_i %>	      
	<% end %>
<% end %>

app/views/items/_status.html.erb

<%- if (item.clearance_batch) and (item.clearance_batch.status.eql? true) and ((item.status.eql? "sellable") || (item.status.eql? "clearanced")) -%>
	<p class="card-text">Item Status: clearanced</p>
	<p class="card-text">Cleared At: <%= item.price_sold %></p>
<%- else -%>
	<p class="card-text">Item Status: <%= item.status %></p>
	<%- if item.status.eql? "clearanced" -%>
		<p class="card-text">Cleared At: <%= item.price_sold %></p> 
	<%- elsif item.status.eql? "sellable" -%>
			<p class="card-text">Estimated Selling Price: <%= item.price_sold %></p> 
	<%- elsif item.status.eql? "sold" -%>			      	
			<p class="card-text">Sold At: <%= item.price_sold %> (Not Available) </p> 
	<% end %>
<%- end -%>

app/views/items/edit.html.erb
<h1>Edit Item Details</h1>

<%= render 'form' %>

app/views/items/new.html.erb
<h1>Enter Item Details</h1>

<%= render 'form' %>

<%= link_to 'Back', @batch,  class: 'btn btn-primary' %>

app/views/items/search.html.erb
<div class="container">

<h1>SEARCH RESULTS</h1>   

<% if @items.present? %>
  <% @items.each do |item| %>

    <div class="card text-center" style="width: 25rem; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
      <div class="card-block">

        <h3 class="card-title">barcode ID: <%= item.id %></h3>          
        <p class="card-text">Size: <%= item.size %></p>
         <div class="card text-center" style="width: 2rem; height: 2rem; border: 1px solid black; background-color: <%= item.color if item.color %>; "></div> 
        
        <p class="card-text">Color: <%= item.color %></p>      
        
        <%= render 'items/status', :item => item %>
          
        <p class="card-text">Created At: <%= l(item.created_at, format: :short) %></p>      
        <p class="card-text">Updated At: <%= l(item.updated_at, format: :short) %></p>

         <%= render 'items/shared', :batchid => @clearance_in.id, :itemid => item.id %>         

        <%= link_to 'Show', clearance_batch_item_path(@clearance_in.id,item.id) %>
      </div>
    </div>

  <% end %>
<% end %>

app/views/items/show.html.erb
<h2>ITEM</h2>
<div class="card text-center" style="width: 90%; padding: 10px 10px; border: 1px solid black; margin: 2px 2px;">
	<div class="card-block">
	<h1>ITEM DESCRIPTION</h1>
		      <h3 class="card-title">Barcode ID: <%= @item.id %></h3> 	      	
		      <p class="card-text">Size: <%= @item.size %></p>
		       <div class="card text-center" style="width: 2rem; height: 2rem; border: 1px solid black; background-color: <%= @item.color if @item.color %>; "></div>	
		      
		      <p class="card-text">Color: <%= @item.color %></p>	     
		      	      	
		      <p class="card-text">Clearance Batch id: <%= @item.clearance_batch_id.to_i if ClearanceBatch.find(@item.clearance_batch_id.to_i) %></p>
		      
		      <%= render 'items/status', :item => @item %>

		      <p class="card-text">Created At: <%= l(@item.created_at, format: :short) %></p>      
		      <p class="card-text">Updated At: <%= l(@item.updated_at, format: :short) %></p>	

	<h1>STYLE DESCRIPTION</h1>

			<p class="card-text">Style Name: <%= @style.name %></p>
			<p class="card-text">Style Id: <%= @style.id %></p>  
		    <p class="card-text">Wholesale Price: <%= @style.wholesale_price %></p>  
		    <p class="card-text">Retail Price: <%= @style.retail_price %></p>  
		    <p class="card-text">Type: <%= @style.type %></p>  
		      
		    <p class="card-text">Style Created At: <%= l(@style.created_at, format: :short) %></p> 
		    <p class="card-text">Style Updated At: <%= l(@style.updated_at, format: :short) %></p>
	</div>
</div>