config/routes.rb
Rails.application.routes.draw do
	
  get 'activities/index'

  devise_for :users

  resources :clearance_batches do #, only: [:index, :create, :destroy]
  	resources :items          
  end
  
  resources :activities

  root "clearance_batches#index" 

  match '/mybatches', to: 'clearance_batches#mybatches', via: :get  
  match '/buy/:id', to: 'clearance_batches#buybatch', via: :get  
  match '/undobatch/:id', to: 'clearance_batches#undobatch', via: :get  

  match '/staffperformance', to: 'pages#staffperformance', via: :get  

  #match '/usecsv', to: 'pages#usecsv', via: :get

  resources :pages, only: [:index, :create, :staffperformance]
  
  

end

app/views/layouts/_admin.html.erb
 <div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'STAFF PERFORMANCE', staffperformance_path %></h4>
</div>

<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'SEE ACTIVITY', activities_path %></h4>
</div>

 <div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'USE CSV', pages_path %></h4>
</div>


app/views/layouts/_notsignin.html.erb
<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'SIGN IN', new_user_session_path %></h4>
</div>

<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'SIGN UP', new_user_registration_path %></h4>
</div>

app/views/layouts/_searchbatch.html.erb

<%= form_tag root_path, method: :get, class: 'navbar-form navbar-right' do %>        
    <%= text_field_tag :search, params[:search], placeholder: 'Search Batch BY ID', class: 'form-control' %>  
    <%= submit_tag 'Search Batch', :name => nil, class: "btn btn-default" %>
<% end %>

app/views/layouts/_searchitem.html.erb
<%= form_tag root_path, method: :get, class: 'navbar-form navbar-right' do %>        
    <%= text_field_tag :searchitem, params[:searchitem], placeholder: 'Search Item By ID', class: 'form-control' %>  
    <%= submit_tag 'Search Item', :name => nil, class: "btn btn-default" %>
<% end %>

app/views/layouts/_signin.html.erb
<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'MY ACCOUNT', edit_user_registration_path %></h4>
</div>
        
<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></h4>
</div>  

app/views/layouts/_staff.html.erb
<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'USE CSV', pages_path %></h4>
</div>

app/views/layouts/_vendor.html.erb
<div class="navbar-header" style="margin:5px 5px">
	<h4><%= link_to 'MY BATCHES', mybatches_path %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clearance Prototype</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">

  
    <a href = "/"><h1 class = "text-center">Stitch Fix Clearance Tool</h1></a>
  
    <% if (user_signed_in?) %>            
        <%= render "layouts/#{current_user.role}" %>
        <%= render "layouts/signin" %>
    <% else %>
      <%= render "layouts/notsignin" %>      
    <% end %>  

  </div>
</nav>

<%= render "layouts/searchbatch" %> 
<%= render "layouts/searchitem" %> 


  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
  <%= yield %>
</div>

</body>
</html>